<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-05-30T22:28:00 IST" name="Default suite" finished-at="2021-05-30T22:29:39 IST" duration-ms="98955">
    <groups>
    </groups>
    <test started-at="2021-05-30T22:28:00 IST" name="Default test" finished-at="2021-05-30T22:29:39 IST" duration-ms="98955">
      <class name="com.EmailValidations.Testcases.TC001_Login_With_MultipleUsers">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.EmailValidations.Testcases.TC001_Login_With_MultipleUsers@43301423]" started-at="2021-05-30T22:28:00 IST" name="setUp" finished-at="2021-05-30T22:28:09 IST" duration-ms="9193" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="login_to_email_account()[pri:0, instance:com.EmailValidations.Testcases.TC001_Login_With_MultipleUsers@43301423]" started-at="2021-05-30T22:28:09 IST" name="login_to_email_account" finished-at="2021-05-30T22:29:37 IST" duration-ms="87597" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Testing] but found [Your Amazon.in order #171-3829123-1405959]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Testing] but found [Your Amazon.in order #171-3829123-1405959]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.EmailValidations.Testcases.TC001_Login_With_MultipleUsers.login_to_email_account(TC001_Login_With_MultipleUsers.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_to_email_account -->
        <test-method is-config="true" signature="tear_Down()[pri:0, instance:com.EmailValidations.Testcases.TC001_Login_With_MultipleUsers@43301423]" started-at="2021-05-30T22:29:38 IST" name="tear_Down" finished-at="2021-05-30T22:29:39 IST" duration-ms="806" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear_Down -->
      </class> <!-- com.EmailValidations.Testcases.TC001_Login_With_MultipleUsers -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
